import React from 'react'

function Recruiters() {
  return (
    <div className="max-w-full m-0 p-5 bg-gray-100">
        <h1 class="text-3xl font-bold text-center my-6">Our Recruiters</h1>
<p class="text-lg leading-relaxed text-gray-700 mx-auto max-w-3xl text-center pb-6">
  The Training and Placement Cell at NIT Kurukshetra conducts all recruitment-related activities for the institute. The placement team works tirelessly to ensure top-notch opportunities are brought to students and manages all interactions between visiting companies and the institute. NIT Kurukshetra assures the best facilities and support possible for the recruiting companies.
</p>

<ul className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-5 justify-center list-none m-0 p-0">
      <li><a href="https://www.aakash.ac.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/akash.jpg" alt="NIT Kurukshetra clients" className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://new.abb.com/power-generation"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/abb.jpg" className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.adani.com/"> <img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/addani.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.accolite.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/Accolite.jpg" alt="" className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://addverb.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/5-1.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.adobe.com/in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/6.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.advancetech.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/7.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.adviserlogic.com"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/8.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.allstateindia.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/9.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.alstom.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/10.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.amazon.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/11.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.americanexpress.com/en-in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/12.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.amity.edu/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/13.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="http://www.amity.edu/kolkata/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/14.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://analyticsindiamag.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/15.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.aryaka.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/16.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.ashokleyland.com/in/en"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/17.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.atkins.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/18.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.atssunriseindia.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/19.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.autodesk.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/20.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://avanti.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/21.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.axslogic.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/22.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.axtria.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/23.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.azcomtech.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/24.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://bchindia.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/25.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.bechtel.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/26.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://blp.co.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/27.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="#"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/28.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.bluestacks.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/29.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://bombardier.com/en"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/30.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.brillio.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/31.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.bsengg.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/32.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.capgemini.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/33.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.cdac.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/34.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.cdot.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/35.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://clairvolex.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/36.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://codenation.org/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/37.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.cvent.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/38.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="#"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/39.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.dbs.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/40.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://decimaltech.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/41.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.delhivery.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/42.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.denso.com/in/en/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/43.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.directi.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/44.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.edifecs.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/45.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="#"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/46.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.emaar.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/47.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="#"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/48.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.envestnet.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/49.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.evelynlearning.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/50.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.evosysglobal.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/51.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.exlservice.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/52.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.feedbackinfra.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/53.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.ficoscore.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/54.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="#"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/55.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.fiserv.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/56.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.ford.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/57.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.fidelity.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/58.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://futuresfirst.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/59.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.ge.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/60.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.ge.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/62.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.gla.ac.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/63.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.godrej.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/64.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.hcltech.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/65.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://hexagon.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/66.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.hitachi.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/67.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.hmel.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/68.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.homecredit.net/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/69.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.honeywell.com/us/en"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/70.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.hughes.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/71.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://i3.consulting/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/72.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.ibm.com/in-en"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/73.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.icicilombard.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/74.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://incture.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/75.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://iocl.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/76.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.iglonline.net/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/77.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.ivp.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/78.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.indxx.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/79.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="http://www.infoedge.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/80.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.infogain.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/81.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.innominds.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/82.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://ictonline.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/83.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.interrasystems.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/84.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://iongroup.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/85.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.jaispring.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/86.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://jivox.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/87.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.jubl.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/88.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://bookmycab.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/89.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.jugnoo.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/90.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://kalpatarupower.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/91.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.lnthydrocarbon.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/92.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.libsys.co.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/93.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="#"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/94.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="http://www.msupply.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/95.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.mahindra.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/96.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://news.samsung.com/global/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/97.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://maqsoftware.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/98.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.marutisuzuki.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/99.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.finastra.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/100.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.motherson.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/101.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.nagarro.com/en"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/102.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://in.nec.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/103.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.niceneotech.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/104.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://newgensoft.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/105.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://niituniversity.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/106.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.nutanix.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/107.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="#"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/108.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.oracle.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/109.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="http://myoxigen.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/110.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.oyorooms.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/111.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://2-power.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/112.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.peoplestrong.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/113.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.philips.co.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/114.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.pinelabs.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/115.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.q3tech.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/117.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.psit.ac.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/116.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://ramboll.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/118.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.rbs.co.uk/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/119.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.jio.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/120.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.ril.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/121.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.rmcindia.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/122.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://sagaciousresearch.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/123.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.saint-gobain.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/124.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.samsung.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/125.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://sapuraenergy.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/126.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.shapoorjipallonji.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/127.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.sidel.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/128.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.siemens.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/129.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.sigmoid.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/130.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="http://www.simplexinfra.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/131.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="http://www.skoolfi.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/132.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.smartprix.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/133.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.smlisuzu.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/134.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.societegenerale.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/135.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="http://www.sprinklersolutionsirrigation.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/136.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.g2.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/137.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.sprinklr.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/138.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://sswlindia.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/139.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.stryker.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/140.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.subros.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/141.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://sunpharma.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/142.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.smlisuzu.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/143.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.supergas.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/144.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://sutraanalytics.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/145.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.synopsys.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/146.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.technipfmc.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/147.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.tegaindustries.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/148.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://triunengineering.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/149.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://toxsl.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/150.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://undostres.com.mx/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/151.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.united.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/152.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.unitedhealthgroup.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/153.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.vecv.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/154.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.vedantalimited.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/155.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.vehant.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/156.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.verizon.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/157.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://westline.co.in/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/158.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.wipro.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/159.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.wsp.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/160.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.zomato.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/161.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.zscaler.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/162.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://zydexindustries.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/163.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.aisglass.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/164.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://coatecindia.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/165.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="http://drishtithevision.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/166.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.medlifemovement.org/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/167.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.ncce.edu/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/168.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.nykaa.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/169.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="http://pjcorp.id/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/170.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="http://www.purnimafoundation.org/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/171.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://bazaar.shopclues.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/172.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.skf.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/173.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.unominda.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/05/174.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.mu-sigma.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/06/microsoft.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
			 <li><a href="https://www.microsoft.com/"><img src="https://nitkkr.ac.in/wp-content/uploads/2022/06/microsoft1.jpg" alt=""className="w-full h-auto max-w-[200px] transition-transform transform hover:scale-110 hover:shadow-lg" /></a></li>
        
      </ul>
    </div>
  )
}

export default Recruiters